config/routes.rb
MonitorBody::Application.routes.draw do
  resources :heights

  resources :weights

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  mount Peek::Railtie => '/peek'
  devise_for :users

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

    if user and user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      can :manage, :all
    end
  end
end

app/models/height.rb
class Height < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_paper_trail

  has_many :weights
  has_many :heights
end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/heights_controller.rb
class HeightsController < ApplicationController
  before_action :set_height, only: [:show, :edit, :update, :destroy]

  # GET /heights
  # GET /heights.json
  def index
    @heights = Height.all
  end

  # GET /heights/1
  # GET /heights/1.json
  def show
  end

  # GET /heights/new
  def new
    @height = Height.new
  end

  # GET /heights/1/edit
  def edit
  end

  # POST /heights
  # POST /heights.json
  def create
    @height = Height.new(height_params)

    respond_to do |format|
      if @height.save
        format.html { redirect_to @height, notice: 'Height was successfully created.' }
        format.json { render action: 'show', status: :created, location: @height }
      else
        format.html { render action: 'new' }
        format.json { render json: @height.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heights/1
  # PATCH/PUT /heights/1.json
  def update
    respond_to do |format|
      if @height.update(height_params)
        format.html { redirect_to @height, notice: 'Height was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @height.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heights/1
  # DELETE /heights/1.json
  def destroy
    @height.destroy
    respond_to do |format|
      format.html { redirect_to heights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_height
      @height = Height.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def height_params
      params.require(:height).permit(:user_id, :cm)
    end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  before_action :set_weight, only: [:show, :edit, :update, :destroy]

  # GET /weights
  # GET /weights.json
  def index
    @weights = Weight.all
  end

  # GET /weights/1
  # GET /weights/1.json
  def show
  end

  # GET /weights/new
  def new
    @weight = Weight.new
  end

  # GET /weights/1/edit
  def edit
  end

  # POST /weights
  # POST /weights.json
  def create
    @weight = Weight.new(weight_params)

    respond_to do |format|
      if @weight.save
        format.html { redirect_to @weight, notice: 'Weight was successfully created.' }
        format.json { render action: 'show', status: :created, location: @weight }
      else
        format.html { render action: 'new' }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weights/1
  # PATCH/PUT /weights/1.json
  def update
    respond_to do |format|
      if @weight.update(weight_params)
        format.html { redirect_to @weight, notice: 'Weight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @weight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weights/1
  # DELETE /weights/1.json
  def destroy
    @weight.destroy
    respond_to do |format|
      format.html { redirect_to weights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weight
      @weight = Weight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weight_params
      params.require(:weight).permit(:kg, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heights_helper.rb
module HeightsHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/heights/_form.html.haml
= form_for @height do |f|
  - if @height.errors.any?
    #error_explanation
      %h2= "#{pluralize(@height.errors.count, "error")} prohibited this height from being saved:"
      %ul
        - @height.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :cm
    = f.text_field :cm
  .actions
    = f.submit 'Save'

app/views/heights/edit.html.haml
%h1 Editing height

= render 'form'

= link_to 'Show', @height
\|
= link_to 'Back', heights_path

app/views/heights/index.html.haml
%h1 Listing heights

%table
  %tr
    %th User
    %th Cm
    %th
    %th
    %th

  - @heights.each do |height|
    %tr
      %td= height.user
      %td= height.cm
      %td= link_to 'Show', height
      %td= link_to 'Edit', edit_height_path(height)
      %td= link_to 'Destroy', height, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Height', new_height_path

app/views/heights/new.html.haml
%h1 New height

= render 'form'

= link_to 'Back', heights_path

app/views/heights/show.html.haml
%p#notice= notice

%p
  %b User:
  = @height.user
%p
  %b Cm:
  = @height.cm

= link_to 'Edit', edit_height_path(@height)
\|
= link_to 'Back', heights_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Monitor Body
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/weights/_form.html.haml
= form_for @weight do |f|
  - if @weight.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weight.errors.count, "error")} prohibited this weight from being saved:"
      %ul
        - @weight.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :kg
    = f.text_field :kg
  .field
    = f.label :user
    = f.text_field :user
  .actions
    = f.submit 'Save'

app/views/weights/edit.html.haml
%h1 Editing weight

= render 'form'

= link_to 'Show', @weight
\|
= link_to 'Back', weights_path

app/views/weights/index.html.haml
%h1 Listing weights

%table
  %tr
    %th Kg
    %th User
    %th
    %th
    %th

  - @weights.each do |weight|
    %tr
      %td= weight.kg
      %td= weight.user
      %td= link_to 'Show', weight
      %td= link_to 'Edit', edit_weight_path(weight)
      %td= link_to 'Destroy', weight, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Weight', new_weight_path

app/views/weights/new.html.haml
%h1 New weight

= render 'form'

= link_to 'Back', weights_path

app/views/weights/show.html.haml
%p#notice= notice

%p
  %b Kg:
  = @weight.kg
%p
  %b User:
  = @weight.user

= link_to 'Edit', edit_weight_path(@weight)
\|
= link_to 'Back', weights_path